"""empty message

Revision ID: 1889020c840c
Revises: 5948f263ad80
Create Date: 2015-07-31 01:38:09.538992

"""

# revision identifiers, used by Alembic.
revision = '1889020c840c'
down_revision = '5948f263ad80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
