"""empty message

Revision ID: 378b575701cd
Revises: 22aa81d71d68
Create Date: 2015-09-01 00:29:00.083366

"""

# revision identifiers, used by Alembic.
revision = '378b575701cd'
down_revision = '22aa81d71d68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
