"""empty message

Revision ID: 3feb5c7a5ffd
Revises: 59ee531902e1
Create Date: 2015-09-21 00:33:16.841289

"""

# revision identifiers, used by Alembic.
revision = '3feb5c7a5ffd'
down_revision = '59ee531902e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
