"""empty message

Revision ID: 5948f263ad80
Revises: None
Create Date: 2015-07-30 23:55:46.140138

"""

# revision identifiers, used by Alembic.
revision = '5948f263ad80'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=18), nullable=True),
    sa.Column('matricula', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('turma',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('turma', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('turma')
    )
    op.create_table('disciplina',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('disciplina')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplina')
    op.drop_table('turma')
    op.drop_table('usuario')
    ### end Alembic commands ###
