"""empty message

Revision ID: 59ee531902e1
Revises: c13fefac542
Create Date: 2015-09-19 21:35:00.720947

"""

# revision identifiers, used by Alembic.
revision = '59ee531902e1'
down_revision = 'c13fefac542'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('usuario_id')

    ### end Alembic commands ###
